# Top navigation menus
author: bbon
menu:
    소개: /about/
    블로그: /archives/

# Site Images
favicon: /favicon.ico
logo: /images/logo-192.png
cover_image_url: /images/logo.png
# Profiles
profile_image_url: /images/me.png
github: 
    username: bbonkr
# Google Analytics
ga: UA-64779499-1
# Twitter
twitter:
    username: '@bbonkr'
# Facebook App
#fb:
#  app_id: ''
#  page: ''
# Google AdSense
#adsense: aaa
# Copyright Infomation
startyear: 2019
