# Top navigation menus
author: bbon
menu:
    소개: /about/
    블로그: /archives/

# Site Images
favicon: /favicon.ico
logo: /images/logo-192.png
cover_image_url: http://image.toast.com/aaaaahq/hola_cover.JPG
# Profiles
profile: /images/me.png
profile_url: https://github.com/bbonkr
# Google Analytics
ga: UA-64779499-1
# Facebook App
#fb:
#  app_id: ''
#  page: ''
# Google AdSense
#adsense: aaa
# Copyright Infomation
startyear: 2019
