menu:
    기초강의: /categories/python
    튜토리얼: /categories/tutorials
    전체보기: /archives/
    깃허브: https://github.com/stunstunstun
    구독하기: /atom.xml

favicon: /favicon.ico
logo: /logo.png

# Comment
disqus: holaxapps
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-97419941-1

# Copyright Infomation
startyear: 2012
