# Site settings
title: "{bbon}"
email: bbon@bbon.me
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://bbon.me"
fixedNav: 'true' # true or false
theme: blue # green, blue, orange, purple, grey
twitterUsername: bbonkr
githubUsername: bbonkr
dribbbleUsername:
codepenUsername:

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages]
exclude: [_site, _drafts, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
