menu:
    기초강의: /categories/python
    블로그: /archives/
    깃허브: https://github.com/stunstunstun
    구독하기: https://www.facebook.com/holaxprogramming
    RSS: http://holaxprogramming.com/atom.xml

favicon: /favicon.ico
logo: /logo.png

# Comment
disqus: holaxapps
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-97419941-1

# Copyright Infomation
startyear: 2012
