menu:
    기초강의: /categories/기초강의
    블로그: /archives/
    구독하기: https://www.facebook.com/holaxprogramming

favicon: /favicon.ico
logo: /logo.png
profile: /profile.jpg
profile_url: https://github.com/stunstunstun

# Comment
disqus: holaxapps

# Analytics
# google-analytics:
ga: UA-97419941-1

# Copyright Infomation
startyear: 2011
