# Header
menu:
  Home: /
  Archives: /archives/
  About: /about/
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: false
widgets:
- category
- tag
- tagcloud
- archives
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
- category
- tagcloud
- archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: 'UA-64779499-1'
gauges_analytics:
favicon: /favicon.ico
twitter: bbonkr
google_plus: 
fb_admins:
fb_app_id: